# Generated by Django 4.2.6 on 2023-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='background_color',
            field=models.CharField(default='#fdddef', max_length=255),
        ),
    ]
