# Generated by Django 4.2.6 on 2023-10-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('brand_name', models.CharField(default='adidas', max_length=255)),
                ('title', models.CharField(default='Cartoon Astronaut T-shirt', max_length=255)),
                ('price', models.IntegerField(default=80)),
            ],
        ),
    ]
